# Generated by Django 4.2.4 on 2023-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_q',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
