POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "hola", "password": "Hola!321!", "email": "hello@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "admin", "password": "admin" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token 66f047842a322a776de6cc52afe0de60e791bd54

###

POST   http://127.0.0.1:8000/api/shop/cart/add/8/
Content-Type: application/json
Authorization: token 906a90a25ddccaa9b6a1f293253bdb62106f3c34


###

DELETE   http://127.0.0.1:8000/api/shop/cart/delete/16/
Content-Type: application/json
Authorization: token 66f047842a322a776de6cc52afe0de60e791bd54