POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "hola", "password": "Hola!321!", "email": "hello@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "admin", "password": "admin" }

###
###

POST   http://127.0.0.1:8000/api/shop/cart/add/8/
Content-Type: application/json
Authorization: token 906a90a25ddccaa9b6a1f293253bdb62106f3c34


###

DELETE   http://127.0.0.1:8000/api/shop/cart/delete/16/
Content-Type: application/json
Authorization: token 66f047842a322a776de6cc52afe0de60e791bd54



###

GET   http://127.0.0.1:8000/api/shop/cart/
Content-Type: application/json
Authorization: token d7f8651f7da094cd538dad9a8c7a67a9893eedb1




###

GET   http://127.0.0.1:8000/api/shop/profile/
Content-Type: application/json
Authorization: token e724b5ea8a20913039415af1cb79760e9a05e3b3





###

GET   http://127.0.0.1:8000/api/shop/product/8/
Content-Type: application/json
Authorization: token 66f047842a322a776de6cc52afe0de60e791bd54


